[project]
name = "mcp-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-google-genai>=2.1.8",
    "langchain-openai>=0.3.28",
    "mcp-use>=1.3.7",
]
